import type { ToolDefinition } from './types';

/**
 * Registry of CLI tools whose configuration/credential location can be redirected per terminal.
 * Add new tools here: each mapping becomes an environment variable pointing into the profile dir.
 *
 * isolation:
 *   full    – config AND credentials live under the redirected location.
 *   partial – config is isolated but some credential/cache path is OS-global (see notes).
 *   shared  – cannot be isolated by the app (listed in LIMITATIONS only).
 */
export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'claude',
    group: 'ai',
    name: 'Claude Code',
    category: 'cli',
    mappings: [{ envVar: 'CLAUDE_CONFIG_DIR', path: 'config/claude', kind: 'dir' }],
    isolation: 'full',
    notes: 'Settings, .claude.json, session history and OAuth credentials (.credentials.json on Windows) are stored in CLAUDE_CONFIG_DIR.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'ANTHROPIC_API_KEY', label: 'Anthropic API key (optional)', help: 'Only if you use Claude Code with an API key instead of a claude.ai login. console.anthropic.com > API keys' }],
  },
  {
    id: 'gcloud',
    group: 'cloud',
    name: 'Google Cloud SDK (gcloud)',
    category: 'cli',
    mappings: [{ envVar: 'CLOUDSDK_CONFIG', path: 'config/gcloud', kind: 'dir' }],
    isolation: 'full',
    notes: 'Accounts, credentials.db, access tokens and application-default credentials live in CLOUDSDK_CONFIG.',
    defaultEnabled: true,
  },
  {
    id: 'gh',
    group: 'code',
    name: 'GitHub CLI (gh)',
    category: 'cli',
    mappings: [{ envVar: 'GH_CONFIG_DIR', path: 'config/github', kind: 'dir' }],
    isolation: 'partial',
    notes:
      'Config and hosts.yml are isolated, but by default gh stores OAuth tokens in Windows Credential Manager (service "gh:github.com"), which is shared by all terminals. ' +
      'For full isolation log in with "gh auth login --insecure-storage" (token kept in this terminal\'s hosts.yml) or set a GH_TOKEN below.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'GH_TOKEN', label: 'GitHub token', help: 'github.com → Settings → Developer settings → Personal access tokens' }],
    whoami: 'gh auth status',
  },
  {
    id: 'git',
    group: 'code',
    name: 'Git (+ Git Credential Manager)',
    category: 'cli',
    mappings: [
      { envVar: 'GIT_CONFIG_GLOBAL', path: 'config/git/.gitconfig', kind: 'file' },
      { envVar: 'GCM_NAMESPACE', path: '', kind: 'value', value: 'omniterminal-{slug}' },
    ],
    isolation: 'full',
    notes:
      'Global git config (user.name, user.email, aliases) is per terminal. Git Credential Manager entries in Windows Credential Manager are namespaced per terminal via GCM_NAMESPACE, ' +
      'so HTTPS logins do not collide. The system gitconfig (Program Files) still applies. For SSH remotes, turn on "SSH key for this terminal".',
    defaultEnabled: true,
  },
  {
    id: 'ssh-key',
    group: 'code',
    name: 'SSH key for this terminal',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes:
      "Git over SSH (in every shell) and ssh/scp/sftp in PowerShell use only this terminal's key and known_hosts, kept in config\\ssh in its folder. " +
      'Create the key here, then add the public key to GitHub or GitLab. Nothing changes until a key exists. Plain ssh in Command Prompt and Git Bash, and the Windows ssh-agent, are still shared.',
    defaultEnabled: false,
  },
  {
    id: 'azure',
    group: 'cloud',
    name: 'Azure CLI (az)',
    category: 'cli',
    mappings: [{ envVar: 'AZURE_CONFIG_DIR', path: 'config/azure', kind: 'dir' }],
    isolation: 'full',
    notes: 'Profiles and the MSAL token cache (DPAPI-encrypted on Windows) live in AZURE_CONFIG_DIR.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'AZURE_DEVOPS_EXT_PAT', label: 'Azure DevOps PAT (optional)', help: 'Used by "az devops" commands. dev.azure.com > User settings > Personal access tokens' }],
  },
  {
    id: 'aws',
    group: 'cloud',
    name: 'AWS CLI',
    category: 'cli',
    mappings: [
      { envVar: 'AWS_CONFIG_FILE', path: 'config/aws/config', kind: 'file' },
      { envVar: 'AWS_SHARED_CREDENTIALS_FILE', path: 'config/aws/credentials', kind: 'file' },
    ],
    isolation: 'partial',
    notes: 'Config and static credentials are isolated. The AWS SSO / CLI token caches (%USERPROFILE%\\.aws\\sso\\cache and \\cli\\cache) are not configurable and remain shared.',
    defaultEnabled: true,
  },
  {
    id: 'kube',
    group: 'cloud',
    name: 'kubectl',
    category: 'cli',
    mappings: [{ envVar: 'KUBECONFIG', path: 'config/kube/config', kind: 'file' }],
    isolation: 'full',
    notes: 'Clusters, contexts and embedded credentials live in KUBECONFIG. Exec auth plugins may keep their own caches.',
    defaultEnabled: true,
  },
  {
    id: 'docker',
    group: 'cloud',
    name: 'Docker CLI',
    category: 'cli',
    mappings: [{ envVar: 'DOCKER_CONFIG', path: 'config/docker', kind: 'dir' }],
    isolation: 'partial',
    notes:
      'config.json is isolated. If a credsStore ("desktop" / "wincred") is configured, registry logins go to Windows Credential Manager and are shared. Without a credsStore, credentials stay in this terminal\'s config.json.',
    defaultEnabled: false,
  },
  {
    id: 'npm',
    group: 'packages',
    name: 'npm user config (.npmrc)',
    category: 'cli',
    mappings: [{ envVar: 'NPM_CONFIG_USERCONFIG', path: 'config/npm/.npmrc', kind: 'file' }],
    isolation: 'full',
    notes: 'Registry auth tokens written by "npm login" go to this terminal\'s .npmrc. The package cache stays shared (no credentials).',
    defaultEnabled: true,
  },
  {
    id: 'huggingface',
    group: 'data',
    name: 'Hugging Face CLI',
    category: 'cli',
    mappings: [{ envVar: 'HF_HOME', path: 'config/huggingface', kind: 'dir' }],
    isolation: 'full',
    notes: 'Token and cache live in HF_HOME. Note: models are re-downloaded per terminal.',
    defaultEnabled: false,
    tokenVars: [{ envVar: 'HF_TOKEN', label: 'Hugging Face token', help: 'huggingface.co > Settings > Access Tokens' }],
  },
  {
    id: 'codex',
    group: 'ai',
    name: 'OpenAI Codex CLI',
    category: 'cli',
    mappings: [{ envVar: 'CODEX_HOME', path: 'config/codex', kind: 'dir' }],
    isolation: 'full',
    notes: 'auth.json, config and sessions live in CODEX_HOME.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'OPENAI_API_KEY', label: 'OpenAI API key (optional)', help: 'platform.openai.com > API keys' }],
  },
  {
    id: 'supabase',
    group: 'deploy',
    name: 'Supabase CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes:
      '"supabase login" saves its token in Windows Credential Manager (or %USERPROFILE%\\.supabase), which is shared by all terminals. ' +
      'For a separate Supabase account per terminal, set the access token below: the CLI uses SUPABASE_ACCESS_TOKEN instead of the saved login. ' +
      'Project links (supabase/config.toml, "supabase link") live in each project folder.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'SUPABASE_ACCESS_TOKEN', label: 'Supabase access token', help: 'supabase.com/dashboard → Account → Access Tokens' }],
    whoami: 'supabase projects list',
  },
  {
    id: 'netlify',
    group: 'deploy',
    name: 'Netlify CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"netlify login" uses a shared global config. Set the token below to use a different Netlify account in this terminal.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'NETLIFY_AUTH_TOKEN', label: 'Netlify token', help: 'app.netlify.com → User settings → Applications → Personal access tokens' }],
    whoami: 'netlify status',
  },
  {
    id: 'fly',
    group: 'deploy',
    name: 'Fly.io (flyctl)',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"fly auth login" writes to %USERPROFILE%\\.fly, shared by all terminals. Set the token below for a per-terminal Fly account.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'FLY_API_TOKEN', label: 'Fly.io token', help: 'fly tokens create org  (or fly.io dashboard → Tokens)' }],
    whoami: 'fly auth whoami',
  },
  {
    id: 'cloudflare',
    group: 'deploy',
    name: 'Cloudflare Wrangler',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"wrangler login" stores OAuth credentials in your user profile, shared by all terminals. Set an API token below for a per-terminal Cloudflare account.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'CLOUDFLARE_API_TOKEN', label: 'Cloudflare API token', help: 'dash.cloudflare.com → My Profile → API Tokens' }],
    whoami: 'wrangler whoami',
  },
  // ---------- more CLIs ----------
  {
    id: 'gemini',
    group: 'ai',
    name: 'Gemini CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: 'Settings live in %USERPROFILE%\\.gemini, shared by all terminals. An API key set here is used instead of the shared login.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'GEMINI_API_KEY', label: 'Gemini API key', help: 'aistudio.google.com > Get API key' }],
  },
  {
    id: 'glab',
    group: 'code',
    name: 'GitLab CLI (glab)',
    category: 'cli',
    mappings: [{ envVar: 'GLAB_CONFIG_DIR', path: 'config/glab', kind: 'dir' }],
    isolation: 'full',
    notes: 'Hosts and tokens from "glab auth login" are stored in GLAB_CONFIG_DIR.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'GITLAB_TOKEN', label: 'GitLab token (optional)', help: 'gitlab.com > Preferences > Access tokens' }],
    whoami: 'glab auth status',
  },
  {
    id: 'oci',
    group: 'cloud',
    name: 'Oracle Cloud CLI (oci)',
    category: 'cli',
    mappings: [{ envVar: 'OCI_CLI_CONFIG_FILE', path: 'config/oci/config', kind: 'file' }],
    isolation: 'full',
    notes: 'Profiles from "oci setup config" go to this terminal\'s config file. Keep the API key files it points to wherever you like.',
    defaultEnabled: true,
  },
  {
    id: 'doctl',
    group: 'cloud',
    name: 'DigitalOcean (doctl)',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"doctl auth init" saves contexts in %APPDATA%\\doctl, shared by all terminals. A token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'DIGITALOCEAN_ACCESS_TOKEN', label: 'DigitalOcean token', help: 'cloud.digitalocean.com > API > Tokens' }],
    whoami: 'doctl account get',
  },
  {
    id: 'helm',
    group: 'cloud',
    name: 'Helm',
    category: 'cli',
    mappings: [{ envVar: 'HELM_CONFIG_HOME', path: 'config/helm', kind: 'dir' }],
    isolation: 'full',
    notes: 'Chart repositories and registry logins are stored in HELM_CONFIG_HOME. Off by default because repos you added globally will not appear here.',
    defaultEnabled: false,
  },
  {
    id: 'terraform',
    group: 'cloud',
    name: 'Terraform',
    category: 'cli',
    mappings: [{ envVar: 'TF_CLI_CONFIG_FILE', path: 'config/terraform/terraform.rc', kind: 'file' }],
    isolation: 'partial',
    notes:
      'CLI settings are per terminal. "terraform login" still writes to %APPDATA%\\terraform.d, so set the HCP Terraform token below for a separate account.',
    defaultEnabled: false,
    tokenVars: [{ envVar: 'TF_TOKEN_app_terraform_io', label: 'HCP Terraform token', help: 'app.terraform.io > User settings > Tokens' }],
  },
  {
    id: 'pulumi',
    group: 'cloud',
    name: 'Pulumi',
    category: 'cli',
    mappings: [{ envVar: 'PULUMI_HOME', path: 'config/pulumi', kind: 'dir' }],
    isolation: 'full',
    notes: 'Login credentials and workspace settings live in PULUMI_HOME. Plugins are downloaded again per terminal.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'PULUMI_ACCESS_TOKEN', label: 'Pulumi access token (optional)', help: 'app.pulumi.com > Personal access tokens' }],
    whoami: 'pulumi whoami',
  },
  {
    id: 'railway',
    group: 'deploy',
    name: 'Railway CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"railway login" is stored in your user profile and shared. A token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'RAILWAY_API_TOKEN', label: 'Railway account token', help: 'railway.com > Account settings > Tokens' }],
    whoami: 'railway whoami',
  },
  {
    id: 'heroku',
    group: 'deploy',
    name: 'Heroku CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"heroku login" writes to your _netrc file, shared by all terminals. An API key set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'HEROKU_API_KEY', label: 'Heroku API key', help: 'dashboard.heroku.com > Account settings > API key' }],
    whoami: 'heroku auth:whoami',
  },
  {
    id: 'expo',
    group: 'deploy',
    name: 'Expo / EAS CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"eas login" is shared by all terminals. An access token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'EXPO_TOKEN', label: 'Expo access token', help: 'expo.dev > Account settings > Access tokens' }],
    whoami: 'eas whoami',
  },
  {
    id: 'stripe',
    group: 'services',
    name: 'Stripe CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"stripe login" stores keys in your user profile, shared by all terminals. A key set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'STRIPE_API_KEY', label: 'Stripe secret key', help: 'dashboard.stripe.com > Developers > API keys (use a test key where you can)' }],
  },
  {
    id: 'sentry',
    group: 'services',
    name: 'Sentry CLI',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"sentry-cli login" writes %USERPROFILE%\\.sentryclirc, shared by all terminals. A token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'SENTRY_AUTH_TOKEN', label: 'Sentry auth token', help: 'sentry.io > User settings > Auth tokens' }],
  },
  {
    id: 'ngrok',
    group: 'services',
    name: 'ngrok',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"ngrok config add-authtoken" writes one shared config file. A token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'NGROK_AUTHTOKEN', label: 'ngrok authtoken', help: 'dashboard.ngrok.com > Your Authtoken' }],
  },
  {
    id: 'pip',
    group: 'packages',
    name: 'pip config (pip.ini)',
    category: 'cli',
    mappings: [{ envVar: 'PIP_CONFIG_FILE', path: 'config/pip/pip.ini', kind: 'file' }],
    isolation: 'full',
    notes: 'Private index URLs and credentials in pip.ini become per terminal. Off by default so your global pip settings keep applying.',
    defaultEnabled: false,
  },
  {
    id: 'cargo',
    group: 'packages',
    name: 'Cargo (crates.io)',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: '"cargo login" writes %USERPROFILE%\\.cargo\\credentials.toml, shared by all terminals. A registry token set here is used instead.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'CARGO_REGISTRY_TOKEN', label: 'crates.io token', help: 'crates.io > Account settings > API tokens' }],
  },
  {
    id: 'deno',
    group: 'packages',
    name: 'Deno',
    category: 'cli',
    mappings: [],
    isolation: 'partial',
    notes: 'Tokens for private module hosts, in the form token@host;token2@host2.',
    defaultEnabled: true,
    tokenVars: [{ envVar: 'DENO_AUTH_TOKENS', label: 'Deno auth tokens', help: 'e.g. ghp_xxx@raw.githubusercontent.com' }],
  },
  {
    id: 'databricks',
    group: 'data',
    name: 'Databricks CLI',
    category: 'cli',
    mappings: [{ envVar: 'DATABRICKS_CONFIG_FILE', path: 'config/databricks/.databrickscfg', kind: 'file' }],
    isolation: 'full',
    notes: 'Workspace profiles and tokens from "databricks configure" or "databricks auth login" are stored in this terminal\'s .databrickscfg.',
    defaultEnabled: true,
  },
  {
    id: 'kaggle',
    group: 'data',
    name: 'Kaggle CLI',
    category: 'cli',
    mappings: [{ envVar: 'KAGGLE_CONFIG_DIR', path: 'config/kaggle', kind: 'dir' }],
    isolation: 'full',
    notes: 'Put this account\'s kaggle.json in the folder above (Kaggle > Settings > Create new token).',
    defaultEnabled: true,
  },
  {
    id: 'bash-history',
    group: 'history',
    name: 'Bash history (Git Bash / WSL)',
    category: 'history',
    mappings: [{ envVar: 'HISTFILE', path: 'history/bash_history', kind: 'file' }],
    isolation: 'full',
    notes: 'Per-terminal bash history. Forwarded into WSL via WSLENV. Ignored if your ~/.bashrc overrides HISTFILE.',
    defaultEnabled: true,
  },
  {
    id: 'node-history',
    group: 'history',
    name: 'Node.js REPL history',
    category: 'history',
    mappings: [{ envVar: 'NODE_REPL_HISTORY', path: 'history/node_repl_history', kind: 'file' }],
    isolation: 'full',
    notes: 'Per-terminal history for the interactive "node" REPL.',
    defaultEnabled: true,
  },
  {
    id: 'python-history',
    group: 'history',
    name: 'Python REPL history',
    category: 'history',
    mappings: [{ envVar: 'PYTHON_HISTORY', path: 'history/python_history', kind: 'file' }],
    isolation: 'full',
    notes: 'Honoured by Python 3.13+.',
    defaultEnabled: true,
  },
];

/** Things the app cannot isolate. Shown in the UI so isolation is never silently overstated. */
export const LIMITATIONS: ToolDefinition[] = [
  {
    id: 'ssh',
    name: 'OpenSSH (ssh, scp, git over SSH)',
    category: 'cli',
    mappings: [],
    isolation: 'shared',
    notes:
      'OpenSSH for Windows always reads %USERPROFILE%\\.ssh and the system-wide ssh-agent service. ' +
      'Turn on "SSH key for this terminal" (Git and PowerShell) to give a terminal its own key; plain ssh in Command Prompt and Git Bash still uses the shared one.',
    defaultEnabled: false,
  },
  {
    id: 'cmd-history',
    name: 'CMD history',
    category: 'history',
    mappings: [],
    isolation: 'shared',
    notes: 'cmd.exe keeps history only in memory (doskey); nothing is persisted or shared between terminals.',
    defaultEnabled: false,
  },
  {
    id: 'wsl-tools',
    name: 'Linux tools inside WSL',
    category: 'cli',
    mappings: [],
    isolation: 'shared',
    notes:
      'Inside a WSL distro, Linux CLIs use the distro\'s $HOME. Only HISTFILE and your custom variables are forwarded (WSLENV). Use a separate distro or a custom variable such as CLAUDE_CONFIG_DIR=/home/you/.claude-x for isolation.',
    defaultEnabled: false,
  },
  {
    id: 'credential-manager',
    name: 'Apps using Windows Credential Manager directly',
    category: 'cli',
    mappings: [],
    isolation: 'shared',
    notes:
      'Any tool that writes to Windows Credential Manager without a configurable namespace (e.g. gh default keyring, Docker credsStore, some VS Code/MSAL-based tools) shares those credentials across terminals.',
    defaultEnabled: false,
  },
  {
    id: 'user-profile',
    name: 'Tools that only use %USERPROFILE% / %APPDATA%',
    category: 'cli',
    mappings: [],
    isolation: 'shared',
    notes:
      'OmniTerminal does not change HOME/USERPROFILE (that would break many tools). CLIs with no config-dir override still share their default location. Add a Custom mapping for any tool that supports an env var.',
    defaultEnabled: false,
  },
];

export const TOOL_GROUPS: { id: NonNullable<ToolDefinition['group']>; label: string }[] = [
  { id: 'ai', label: 'AI coding tools' },
  { id: 'code', label: 'Git and code hosting' },
  { id: 'cloud', label: 'Cloud and infrastructure' },
  { id: 'deploy', label: 'Hosting and deploys' },
  { id: 'services', label: 'Developer services' },
  { id: 'packages', label: 'Package managers' },
  { id: 'data', label: 'Data and ML' },
  { id: 'history', label: 'Shell and REPL history' },
];

export function getTool(id: string): ToolDefinition | undefined {
  return TOOL_REGISTRY.find((t) => t.id === id);
}

export function isToolEnabled(tools: Record<string, boolean>, def: ToolDefinition): boolean {
  return tools[def.id] ?? def.defaultEnabled;
}
